### ISSUE TITLE
difference between electrode-react-ssr-caching?

### ISSUE THREAD

**Issue by voidale** [walmartlabs/react-ssr-optimization#10]
Hey can't figure out what should I use, what is the difference?

**Comment by maximenajim** [comment]
Hi @voidale, this `react-ssr-optimization` library was developed as part of our findings when we initially started using React's server side rendering.  We wanted to get this library out as soon as we possible could as a reference implementation to get feedback from the open source community.  The concepts and approaches we took with this library were later groomed and folded into the `electrode.io` project which now includes additional features like profiling, etc.  That being said, this is still very much a functioning library, so feel free to use either.
