### ISSUE TITLE
Cache based on context

### ISSUE THREAD

**Issue by petermikitsh** [walmartlabs/react-ssr-optimization#14]
Looking at the `keyGenerator` function in the docs, it appears to have this method signature:

`function keyGenerator(props) { ... }`

Is it possible to inspect context as well? I would need to include data from the context in my key.

Thanks!

**Comment by maximenajim** [comment]
@petermikitsh interesting thought, but we haven't had a need for passing down the context.  Is this something you'd be interested in contributing?

**Comment by petermikitsh** [comment]
My requirements have changed, this would no longer be needed. Would be a cool idea for someone else to work on, if they had the need for it.
