### ISSUE TITLE
Webpack integration

### ISSUE THREAD

**Issue by petermikitsh** [walmartlabs/react-ssr-optimization#15]
I'm having issues using this module with webpack. For example, here is my app:

```js
const componentOptimization = require('react-ssr-optimization');
import React from 'react';
import ReactDomServer from 'react-dom/server';

const componentOptimizationRef = componentOptimization({
  components: {
    HelloWorld: function (props) {
      console.log('in HelloWorld cache check function'); // eslint-disable-line
      return props.text;
    }
  },
  lruCacheSettings: {
    max: 500
  }
});

let renderCount = 0;

class HelloWorld extends React.Component {
  render() {
    renderCount++;
    return React.DOM.div(null, this.props.text);
  }
}

HelloWorld.propTypes = {
  text: React.PropTypes.string
};

// Cache Miss
ReactDomServer.renderToString(React.createFactory(HelloWorld)({text: "Hello World X!"}));
console.log('renderCount is', renderCount);

// Cache Hit
ReactDomServer.renderToString(React.createFactory(HelloWorld)({text: "Hello World X!"}));
console.log('renderCount is', renderCount);

setInterval(() => {
  console.log('cache length is', componentOptimizationRef.cacheLength()); // eslint-disable-line
}, 3000);
```

After bundling and executing, this is the output:

```
renderCount is 1
renderCount is 2
cache length is 0
cache length is 0
cache length is 0
cache length is 0
cache length is 0
...
```

**Comment by petermikitsh** [comment]
I tried using babel-node directly (bypassing webpack-- e.g., `NODE_ENV=production babel-node server/example.js`) and I'm still not seeing the cache being used.

**Comment by petermikitsh** [comment]
I've created an example repo here: https://github.com/petermikitsh/react-ssr-optimization-demo

It doesn't use webpack or babel -- pure node. I cloned this repo and ran the tests and they succeeded so I'm unsure of how to properly utilize this module.

**Comment by petermikitsh** [comment]
I'm going to close this out. I switched over to https://github.com/electrode-io/electrode-react-ssr-caching. Hopefully this will help others that may come across it:

The key was to set the following webpack (1.x) externals:

```js
  externals: {
    'react-dom/server': "require('react-dom/server')",
    'electrode-react-ssr-caching': "require('electrode-react-ssr-caching')"
  },
```

and add the following plugin to my webpack config:

```js
  plugins: [
   new webpack.BannerPlugin(
    'global.SSRCaching = require("electrode-react-ssr-caching");',
      {
        raw: true,
        entryOnly: false
      }
    )
  ],
```

The full example has been updated at https://github.com/petermikitsh/react-ssr-optimization-demo.

**Comment by StephenGrider** [comment]
@petermikitsh You might find this useful:

This lib works fine with webpack - if you're finding that it isn't working chances are your webpack config is accidentally pulling React into the output bundle.  

React-ssr-optimization attempts to `require` and wrap a few functions from react-dom.  However, if your webpack build is including React into the bundle, then you'll end up dealing with two copies of React - one that is included in the webpack bundle (this is the one that actually gets used in your app), and a second that gets required by react-ssr-optimization.

The key is to ensure that Webpack isn't including ReactDOM.  Easiest way to do that is to use something like https://github.com/liady/webpack-node-externals.  You can check to see if webpack is erroneously pulling in React by building your bundle with `webpack -p` and then searching for 'React' in that file.  If you see React library code then chances are you're running into the above mentioned problem.
