### ISSUE TITLE
Avoid caching a component because of a prop

### ISSUE THREAD

**Issue by miduga** [walmartlabs/react-ssr-optimization#17]
So, imagine I've a component that changes his behaviour for logged users. I think that's not worth it to cache that component as it will literally fill the cache with components that are not used as some general ones. Is there any way to avoid caching by a prop? For example, returning false?

If not, is it something that you consider? Is something that if you get a PR will be glad to merge?

Thanks!

**Comment by maximenajim** [comment]
Hi @miduga, if your cacheKey generator function starts returning `null` for the component for logged users, then this library will avoid caching it.  Please see:
Code: https://github.com/walmartlabs/react-ssr-optimization/blob/master/lib/index.js#L159
Test: https://github.com/walmartlabs/react-ssr-optimization/blob/master/test/spec/index.spec.js#L126

You can also look at templatization to cache part of the rendered component that doesn't contain any user specific data, please see: https://github.com/walmartlabs/react-ssr-optimization#how-you-use-component-templatization

**Comment by miduga** [comment]
Awesome! Thanks!
