### ISSUE TITLE
Is react and react-dom required in package.json?

### ISSUE THREAD

**Issue by withgallantry** [walmartlabs/react-ssr-optimization#2]
Have react and react-dom listed in package.json causes NPM to create a local copy of the library. Running two versions of React then create an incompatibility between the library and React.
This was tested with the main application package.json containing version ^15.3.0 and electrode-react-srr-optimiziation containing ^0.14.8.

I understand versioning is required so you can maintain compatibility with released React versions but in this instance it has caused an incompatibility.

**Comment by bhoule** [comment]
https://github.com/electrode-io/electrode-react-ssr-caching supports React 15.3.0 as a peer dependency, so that repository might be a better option.

**Comment by maximenajim** [comment]
@withgallantry @bhoule I've made React 15.X as a peer dependency to this library now: https://github.com/walmartlabs/react-ssr-optimization/blob/master/package.json#L46
