### ISSUE TITLE
Feature Request: Allow environment setting REACT_SSR_OPTIMIZATION_ENV with fallback to NODE_ENV

### ISSUE THREAD

**Issue by JustinMGaiam** [walmartlabs/react-ssr-optimization#7]
Before we start working with this library I wanted to test out the result of caching locally to make sure I am setting the caching strategy variables `templateAttrs` and `cacheAttrs` correctly i.e. I want to make sure I don't miss a variable in `cacheAttrs` that could cause a incorrect cached response.  This is also something that would be helpful to other developers when making component changes so they can confirm they did not break the caching strategy or to write tests around the caching strategy.  Currently the library uses `NODE_ENV` exclusively, but it would be helpful to have a specific env var maybe `REACT_SSR_OPTIMIZATION_ENV` with a fallback to `NODE_ENV`.  Looks like all that would have to change is this line https://github.com/walmartlabs/react-ssr-optimization/blob/master/lib/index.js#L44 so if this makes sense let me know and I can submit a PR.

**Comment by maximenajim** [comment]
Hi @JustinMGaiam, I recall React throwing errors like `Can't add property _instantiateReactComponent, object is not extensible` when running with NODE_ENV=test.   Have you had better luck with running this library when `NODE_ENV !== "production"`?

Thinking through your requirements a bit, perhaps a better possible approach would be to implement a "profiling" or "simulation" mode that when enabled would make this library collect and output data points around things like the cache keys that were used for a given execution.  This could also help to automate tests around different caching variables and fit nicely in a CI pipeline that could assert on the profiling/simulation mode output to ensure things don't break when developers make changes to components you are trying to cache/optimize.

**Comment by JustinMGaiam** [comment]
@maximenajim the values that you suggested ("profiling" or "simulation") for those use cases make sense.  I was not able to get this working in our code base, but that was before it looks like a few commits were made recently.  When I get some spare time I will try it again.

**Comment by maximenajim** [comment]
@JustinMGaiam please try the latest version and let us know how it goes.  I'll close this issue for now.  Thank you.
